### ISSUE TITLE
Duplicate actions with joypads in 4.1.2

### ISSUE THREAD

**Issue by Macklehatton** [matjlars/godot-multiplayer-input#4]
Using version v4.1.2.stable.official [399c9dc39].

I'm getting an error `InputMap already has action "Xaction"` with any number of joypads connected. This appears to only occur for actions I've added to the InputMap, not the default actions. If I have one joypad connected with one action assigned-- "join"-- I receive the following error.

```E 0:00:02:0296   multiplayer_input.gd:79 @ _create_actions_for_device(): InputMap already has action "0join".
  <C++ Error>    Condition "input_map.has(p_action)" is true.
  <C++ Source>   core\input\input_map.cpp:89 @ InputMap::add_action()
  <Stack Trace>  multiplayer_input.gd:79 @ _create_actions_for_device()
                 multiplayer_input.gd:59 @ _on_joy_connection_changed()
```

It appears `_create_actions_for_device` is being called twice. Once in `reset` and again at some point when the game starts and `_on_joy_connection_changed` fires for the already connected joypad.

The problem occurs in version 4.1.2 and not 4.1.1. The following did not fix the issue: Reloading the project, removing and re-adding the plugin, deleting and regenerating the .godot folder, removing all inputs from project.godot.

Commenting out this code at lines 44-45 of multiplayer_input.gd appears to fix the problem.
```
for device in Input.get_connected_joypads():
		_create_actions_for_device(device)
```
This fixes it in the editor and builds. This solution is acceptable for me so the issue is not urgent. Posting this for others and to let you know the behavior of `Input.joy_connection_changed` has changed. From the 4.1.2 changelog, something around this issue may be related https://github.com/godotengine/godot/pull/76045.

**Comment by symbol24** [comment]
I also had the same issue. I added a check before adding new inputs so that it doesnt add a new input if it already exists

**Comment by matjlars** [comment]
Hi can somebody test this now that I merged in #3

**Comment by andersmmg** [comment]
I still get the same errors with this, the error goes away if I comment out this section:
```gdscript
	# create actions for already connected gamepads
	for device in Input.get_connected_joypads():
		_create_actions_for_device(device)
```
And it seems to work fine. Why is this required?

**Comment by Macklehatton** [comment]
I still see the same errors and still get the same effect from the workaround, same as @andersmmg.

It appears `_on_joy_connection_changed` is firing for us even for joypads that are already connected when the game starts. Is this not expected behavior?

**Comment by willerxxmiller** [comment]
> Hi can somebody test this now that I merged in #3

I don't know that this commit fixes anything. The ignore array is never populated.

**Comment by matjlars** [comment]
@andersmmg and @Macklehatton I needed to call those on already-connected gamepads on mine. I wonder if it's a Godot version difference? Or maybe a platform difference? I built this plugin for a game back in... 4.0 alpha maybe?  I'll try it with 4.2 on my Windows machine to see what behavior I see.

**Comment by matjlars** [comment]
Ok yep, good call @Macklehatton and everybody else! I just confirmed this and fixed it in the main branch. I also submitted it for approval on the Godot asset library. Thanks everybody!
